name: CI

on: 
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: codfish/semantic-release-action@master
    env:
      GITHUB_TOKEN: ${{ secrets.GB_TOKEN }}
